In [24]:
pip install numpy

Requirement already satisfied: numpy in c:\Users\boody\miniconda3\Lib\site-packages (2.4.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\boody\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\Users\boody\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.7 MB 3.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.7 MB 3.9 MB/s eta 0:00:02
   ----------- ---------------------------- 2.9/9.7 MB 3.9 MB/s eta 0:00:02
   --------------- ------------------------ 3.7/9.7 MB 3.9 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.7 MB 3.9 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.7 MB 3.9 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.7 MB 3.9 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.7 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 3.9 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.7 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 3.9 MB/s  0:00:02
Downloading numpy-2.4.2-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 4.0 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.3 MB 3.8 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.3 MB 3.8 MB/s eta 0:00:03
   ---------- ----------------------------- 3.1/12.3 MB 3.8 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.3 MB 3.8 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.3 MB 3.8 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.3 MB 3.8 MB/s eta 0:00:02
   -------------------- ------------------- 6.3/12.3 MB 3.7 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.3 MB 3.7 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.3 MB 3.7 MB/s eta 0:00:02
   --------------------------- ------------ 8.4/12.3 MB 3.7 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.3 MB 3.7 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.3 MB 3.7 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 3.7 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 3.7 MB/s  0:00:03
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.2 pandas-3.0.1 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np

In [3]:
# 1.Load the file students.csv and make sure Score Date is parsed as datetime. 
import pandas as pd 


df = pd.read_csv('students.csv', parse_dates=['Score Date'])

In [35]:
#2. Print the shape, columns list, and data types of the DataFrame.
print(df.shape)
print(df.dtypes)

(9, 8)
Student ID             int64
Name                     str
Age                    int64
Grade                float64
Subject                  str
City                     str
Passed                  bool
Score Date    datetime64[us]
dtype: object

In [36]:
#3. Show the first 7 rows and the last 3 rows. 
print(df.head(7))
print(df.tail(3))

   Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2    Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3    Omar   19   65.0       Math        Giza   False 2025-01-20
3           4    Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5  Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6    Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7    Yara   30   89.0       Math       Cairo    True        NaT
   Student ID     Name  Age  Grade    Subject   City  Passed Score Date
6           7     Yara   30   89.0       Math  Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12

In [37]:
#4. Show how many missing values in each column. 
print(df.isnull().sum())

Student ID    0
Name          0
Age           0
Grade         1
Subject       0
City          0
Passed        0
Score Date    1
dtype: int64

In [9]:
#5. What is the average, minimum, and maximum Grade?
print(df.Grade.mean())
print(df.Grade.min())
print(df.Grade.max())

76.375
55.0
92.0

In [ ]:
#6. How many unique cities are there? List them. 
print(df.City.unique())

<StringArray>
['Cairo', 'Alexandria', 'Giza', 'Mansoura']
Length: 4, dtype: str

In [13]:
#7. Use value_counts() to show how many students per Subject. 
print(df.Subject.value_counts())

Subject
Math         3
Chemistry    3
Physics      2
English      1
Name: count, dtype: int64

In [14]:
#8. Select only the columns: Name, Grade, Subject, City.
print(df[['Name','Grade','Subject','City']])

      Name  Grade    Subject        City
0    Ahmed   88.0       Math       Cairo
1     Sara   92.0    Physics  Alexandria
2     Omar   65.0       Math        Giza
3     Lina   78.0  Chemistry       Cairo
4   Khaled   55.0    Physics    Mansoura
5     Nour    NaN    English  Alexandria
6     Yara   89.0       Math       Cairo
7  Mohamed   72.0  Chemistry        Giza
8  Mohamed   72.0  Chemistry        Giza

In [18]:
#9.Show all students who Passed and have Grade ≥ 85.
df_passed = df[(df['Passed'] == True) & (df['Grade'] >= 85)]
print(df_passed)

   Student ID   Name  Age  Grade  Subject        City  Passed Score Date
0           1  Ahmed   25   88.0     Math       Cairo    True 2025-01-15
1           2   Sara   32   92.0  Physics  Alexandria    True 2025-02-10
6           7   Yara   30   89.0     Math       Cairo    True        NaT

In [19]:
#10. Show students whose Name contains the letter "a" or "A" (case insensitive). 
df_named = df[df['Name'].str.contains('a', case=False)]
print(df_named)

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [20]:
#11. Show students in Cairo or Alexandria with Grade < 80. 
df_occ = df[(df['City'].isin(['Cairo', 'Alexandria'])) & (df['Grade'] < 80)]
print(df_occ)

   Student ID  Name  Age  Grade    Subject   City  Passed Score Date
3           4  Lina   28   78.0  Chemistry  Cairo    True 2025-03-05

In [21]:
#12.Show students with Grade between 80 and 90 (inclusive).
df_range = df[(df['Grade'] >=80 ) & (df['Grade']<=90)]
print(df_range)

   Student ID   Name  Age  Grade Subject   City  Passed Score Date
0           1  Ahmed   25   88.0    Math  Cairo    True 2025-01-15
6           7   Yara   30   89.0    Math  Cairo    True        NaT

In [22]:
df

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6     Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [23]:
#13. Using .loc, change Khaled's grade from 55 to 68.
df.loc[df['Name'] == 'Khaled', 'Grade'] = 68
df

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   68.0    Physics    Mansoura   False 2025-02-28
5           6     Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [38]:
#14.Add a new column Is_Excellent that is True if Grade ≥ 90, False otherwise (vectorized).
df['Is_Excellent'] = np.where(df['Grade'] >= 90,True, False)
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True
2,3,Omar,19,65.0,Math,Giza,False,2025-01-20,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False
4,5,Khaled,45,55.0,Physics,Mansoura,False,2025-02-28,False
5,6,Nour,22,NaN,English,Alexandria,True,2025-01-10,False
6,7,Yara,30,89.0,Math,Cairo,True,NaT,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False

In [39]:
# 15.Fill missing Grade values with the average Grade. 
df['Grade'] = df['Grade'].fillna(df['Grade'].mean())

In [42]:
# 16.Fill missing Score Date values with the most common date (mode). 

df['Score Date'] = df['Score Date'].fillna(df['Score Date'].mode()[0])
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.000,Math,Cairo,True,2025-01-15,False
1,2,Sara,32,92.000,Physics,Alexandria,True,2025-02-10,True
2,3,Omar,19,65.000,Math,Giza,False,2025-01-20,False
3,4,Lina,28,78.000,Chemistry,Cairo,True,2025-03-05,False
4,5,Khaled,45,55.000,Physics,Mansoura,False,2025-02-28,False
5,6,Nour,22,76.375,English,Alexandria,True,2025-01-10,False
6,7,Yara,30,89.000,Math,Cairo,True,2025-03-12,False
7,8,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False
8,8,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False

In [45]:
#17. Add a new column Final_Grade = Grade + 5 (bonus points). 
df['Final_Grade'] = df['Grade'] +5
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade
0,1,Ahmed,25,88.000,Math,Cairo,True,2025-01-15,False,93.000
1,2,Sara,32,92.000,Physics,Alexandria,True,2025-02-10,True,97.000
2,3,Omar,19,65.000,Math,Giza,False,2025-01-20,False,70.000
3,4,Lina,28,78.000,Chemistry,Cairo,True,2025-03-05,False,83.000
4,5,Khaled,45,55.000,Physics,Mansoura,False,2025-02-28,False,60.000
5,6,Nour,22,76.375,English,Alexandria,True,2025-01-10,False,81.375
6,7,Yara,30,89.000,Math,Cairo,True,2025-03-12,False,94.000
7,8,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000
8,8,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000

In [48]:
#18. Create a column Grade_Category using pd.cut with bins:
    # •0–69 → "Fail" 
    # •70–79 → "Average" 
    # •80–89 → "Good" 
    # •90–100 → "Excellent" 
df['Grade_Category'] = pd.cut(df['Grade'],
                              bins=[0,70,80,90,100],
                              labels=['Fail', 'Average', 'Good', 'Excellent'],
                              include_lowest=True)
df

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,1,Ahmed,25,88.000,Math,Cairo,True,2025-01-15,False,93.000,Good
1,2,Sara,32,92.000,Physics,Alexandria,True,2025-02-10,True,97.000,Excellent
2,3,Omar,19,65.000,Math,Giza,False,2025-01-20,False,70.000,Fail
3,4,Lina,28,78.000,Chemistry,Cairo,True,2025-03-05,False,83.000,Average
4,5,Khaled,45,55.000,Physics,Mansoura,False,2025-02-28,False,60.000,Fail
5,6,Nour,22,76.375,English,Alexandria,True,2025-01-10,False,81.375,Average
6,7,Yara,30,89.000,Math,Cairo,True,2025-03-12,False,94.000,Good
7,8,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000,Average
8,8,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000,Average

In [49]:
#19. Remove the column Student ID. 
df= df.drop(columns = 'Student ID')

In [50]:
#20.Keep only students who Passed. 
df_passed = df[df['Passed'] == True]
df_passed

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Ahmed,25,88.000,Math,Cairo,True,2025-01-15,False,93.000,Good
1,Sara,32,92.000,Physics,Alexandria,True,2025-02-10,True,97.000,Excellent
3,Lina,28,78.000,Chemistry,Cairo,True,2025-03-05,False,83.000,Average
5,Nour,22,76.375,English,Alexandria,True,2025-01-10,False,81.375,Average
6,Yara,30,89.000,Math,Cairo,True,2025-03-12,False,94.000,Good
7,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000,Average
8,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000,Average

In [51]:
#21. Sort the DataFrame by Grade descending. 
df_sorted = df.sort_values(by='Grade', ascending=False)
df_sorted

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,Sara,32,92.000,Physics,Alexandria,True,2025-02-10,True,97.000,Excellent
6,Yara,30,89.000,Math,Cairo,True,2025-03-12,False,94.000,Good
0,Ahmed,25,88.000,Math,Cairo,True,2025-01-15,False,93.000,Good
3,Lina,28,78.000,Chemistry,Cairo,True,2025-03-05,False,83.000,Average
5,Nour,22,76.375,English,Alexandria,True,2025-01-10,False,81.375,Average
7,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000,Average
8,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000,Average
2,Omar,19,65.000,Math,Giza,False,2025-01-20,False,70.000,Fail
4,Khaled,45,55.000,Physics,Mansoura,False,2025-02-28,False,60.000,Fail

In [52]:
#22. Sort by City ascending, then inside each city sort by Grade descending.
df_sorted_city = df.sort_values(by=['City', 'Grade'], ascending=[True, False])
df_sorted_city

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,Sara,32,92.000,Physics,Alexandria,True,2025-02-10,True,97.000,Excellent
5,Nour,22,76.375,English,Alexandria,True,2025-01-10,False,81.375,Average
6,Yara,30,89.000,Math,Cairo,True,2025-03-12,False,94.000,Good
0,Ahmed,25,88.000,Math,Cairo,True,2025-01-15,False,93.000,Good
3,Lina,28,78.000,Chemistry,Cairo,True,2025-03-05,False,83.000,Average
7,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000,Average
8,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000,Average
2,Omar,19,65.000,Math,Giza,False,2025-01-20,False,70.000,Fail
4,Khaled,45,55.000,Physics,Mansoura,False,2025-02-28,False,60.000,Fail

In [53]:
#23. Add a column Rank that ranks students by Grade (1 = highest, handle ties with 'min').
df['Rank'] = df['Grade'].rank(method ='min',
                              ascending=False)

df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
0,Ahmed,25,88.000,Math,Cairo,True,2025-01-15,False,93.000,Good,3.0
1,Sara,32,92.000,Physics,Alexandria,True,2025-02-10,True,97.000,Excellent,1.0
2,Omar,19,65.000,Math,Giza,False,2025-01-20,False,70.000,Fail,8.0
3,Lina,28,78.000,Chemistry,Cairo,True,2025-03-05,False,83.000,Average,4.0
4,Khaled,45,55.000,Physics,Mansoura,False,2025-02-28,False,60.000,Fail,9.0
5,Nour,22,76.375,English,Alexandria,True,2025-01-10,False,81.375,Average,5.0
6,Yara,30,89.000,Math,Cairo,True,2025-03-12,False,94.000,Good,2.0
7,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000,Average,6.0
8,Mohamed,27,72.000,Chemistry,Giza,True,2025-03-12,False,77.000,Average,6.0

In [56]:
#24. Show the top 4 students with the highest grades (use nlargest). 
top_students = df.nlargest(4, 'Grade')
top_students

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average,4.0

In [57]:
#25. Show the 3 youngest students (use nsmallest on Age).
youngest_students = df.nsmallest(3, 'Age')
youngest_students

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
2,Omar,19,65.000,Math,Giza,False,2025-01-20,False,70.000,Fail,8.0
5,Nour,22,76.375,English,Alexandria,True,2025-01-10,False,81.375,Average,5.0
0,Ahmed,25,88.000,Math,Cairo,True,2025-01-15,False,93.000,Good,3.0

In [ ]:
#26.Find the student(s) with the highest Grade and show their Name and Grade. 

df.nlargest(1, 'Grade').groupby('Name').head()

   Student ID  Name  Age  Grade  Subject        City  Passed Score Date
1           2  Sara   32   92.0  Physics  Alexandria    True 2025-02-10

In [12]:
df.nlargest(3, 'Grade').groupby('Name').head()

   Student ID   Name  Age  Grade  Subject        City  Passed Score Date
1           2   Sara   32   92.0  Physics  Alexandria    True 2025-02-10
6           7   Yara   30   89.0     Math       Cairo    True        NaT
0           1  Ahmed   25   88.0     Math       Cairo    True 2025-01-15